### ISSUE TITLE
Fix netlify bot duplication

### ISSUE THREAD

**Issue by yndajas** [dxw/accessibility-manual#11]
The netlify bot seems to be working overtime - it's responding to each new PR twice, e.g. #8 and #9 (I deleted the first comment on #10). You can see it comments on the PR and then immediately comments again, and then the deploy preview on the first becomes invalid

I'm not sure if this is something to do with the Netlify site settings, which are linked in each of the bot's comments. I don't have permissions to view/edit them, so I can't check what options are there

**Comment by yndajas** [comment]
Perhaps related: https://answers.netlify.com/t/build-is-triggered-twice/1646 (and linked within: https://answers.netlify.com/t/multiple-builds-triggered-for-each-commit-or-push/900)

**Comment by snim2** [comment]
There are no webhooks in the repo. Netlify is added as an app, with permissions for each repository that it needs access to.

I notice we have pending requests to add Netlify to the org, even though that has already happened. I'll reject the latest request and see what happens...

**Comment by snim2** [comment]
Is this still happening?

**Comment by yndajas** [comment]
> Is this still happening?

_15 months later_

Yep!

**Comment by yndajas** [comment]
@snim2 discovered that we had the site registered in Netlify under two accounts. Deleting the site from one account (the one that wasn't doing the deploys - and also wasn't building working previews) fixed this issue
