### ISSUE TITLE
Redesign navigation on smaller screens

### ISSUE THREAD

**Issue by lookupdaily** [dxw/accessibility-manual#91]
On smaller screens site navigation uses a horizontal scroll which isn't very user friendly. 

Since adding additional hierarchical context into the navigation in #90, this horizontal scrollable menu is even more unusable, as each item in the horizontal bar can toggle vertically. 

Ideally we would like to have an expandable 'hamburger' menu for smaller screens, which retains the same behaviour as the side navigation on larger screens. 

Current menu on smaller screens:
<img width="692" alt="image" src="https://github.com/dxw/accessibility-manual/assets/50752284/45d4b75d-4b2a-4d34-8863-407497e51cc1">

Menu on smaller screens following update in #90 
<img width="651" alt="image" src="https://github.com/dxw/accessibility-manual/assets/50752284/8bb7d835-ccd7-4af0-9e61-2ca2405ded83">

**Comment by yndajas** [comment]
@lookupdaily should this have been closed by #90?
